apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui-component
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ui-component
  template:
    metadata:
      labels:
        app: ui-component
    spec:
      containers:
        - name: ui
          image: carlguan/datastack-poc-ui-component:latest
          env:
            - name: PORT
              value: "8080"
