apiVersion: v1
kind: Service
metadata:
  name: db-component
spec:
  ports:
    # by specifying one port, this is equivalent 
    # to setting both the port and targetPort to 5432
    - port: 5432
  selector:
    app: db-component
  # this is the default service type
  # type: ClusterIP 
